[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
    name = "github.com/gorilla/websocket"
    version = "1.4.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  branch = "master"

[[constraint]]
  name = "github.com/orcaman/concurrent-map"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
