# 1m, 3m, 15m, 30m, 1h, 4h, 1d, 1week
k-line-interval = [60, 180, 300, 900, 1800, 3600, 14400, 86400, 604800]

[http]
proxy = "http://127.0.0.1:1087"
timeout = 1000

[exchange]
    [exchange.bitmex]
    api-key = ""
    api-secret = ""
    address = ""
    symbols = ["XBTUSD"]
    topic = ["trade", "quote", "position", "order", "orderBookL2_25"]
    http-url = ""

    [exchange.huobi]
    api-key = ""
    api-secret = ""
    address = ""
    symbols = []
    topic = []
    http-url = ""

[websocket]
# read wait timeout (ms)
read-wait = 10000
# write wait timeout (ms)
write-wait = 10000
# heartbeat duration (s)
heartbeat-duration = 10
retry = 5

[storage]
storage-type = "csv"
    [storage.csv]
    data-dir = ""

[log]
# Log file path, if the value is "", it means output to stdout
log-file = ""
# Log level, ONLY in "debug", "info", "warn", "error", "fatal"
log-level = "info"
# Log format, ONLY in "json", "text", "console", "highlight"
log-format = "text"
# Is log rotate enabled.
LogRotate = true
# Max size for a single file, in MB.
MaxSize = 500
# Max log keep days, default is never deleting.
MaxDays = 14
# Maximum number of old log files to retain.
MaxBackups = 64
